version: 2
sources:
  - name: raw
    database: refined-bolt-479015-v6
    schema: gz_raw_data
    loader: bigquery
    tables:
      - name: adwords
        identifier: raw_gz_adwords
        description: date_date, paid_source, campaign_key, campaign_name, ads_cost, impression, click
        columns:
          - name: date_date
            description: "Fecha de la métrica de campaña"
            tests:
              - not_null
              - dbt_utils.expression_is_true:
                  arguments:
                    expression: "date_date <= CURRENT_DATE()"
                  severity: warn                  
          - name: paid_source
            description: "Canal de publicidad"
            tests:
              - not_null
              - dbt_utils.accepted_values:
                  arguments:
                    column_name: paid_source
                    values: ["Adwords", "Bing", "Criteo", "Facebook"]
                  severety: error
          - name: campaign_key
            description: "Identificador único de la campaña"
            tests:
              - not_null
          - name: campaign_name
            description: "Nombre legible de la campaña"
            tests:
              - not_null
          - name: ads_cost
            description: "Costo total de los anuncios en USD"
            tests:
                - not_null
                - dbt_utils.expression_is_true:
                    arguments:
                      expression: "ads_cost >= 0"
                    severity: error
          - name: impression
            description: "Número de impresiones"
            tests:
              - not_null
              - dbt_utils.expression_is_true:
                  arguments:
                    expression: "impression >= 0"
                  severity: error
          - name: click
            description: "Número de clics"
            tests:
              - not_null
              - dbt_utils.expression_is_true:
                  arguments:
                    expression: "click >= 0"
                  severity: error
        tests:
          - dbt_utils.unique_combination_of_columns:
              arguments:
                combination_of_columns:
                  - date_date
                  - campaign_key
                  - paid_source
              severity: error
      - name: bing
        identifier: raw_gz_bing
        description: date_date, paid_source, campaign_key, campaign_name, ads_cost, impression, click
      - name: criteo
        identifier: raw_gz_criteo
        description: date_date, paid_source, campaign_key, campaign_name, ads_cost, impression, click
      - name: facebook
        identifier: raw_gz_facebook
        description: date_date, paid_source, campaign_key, campaign_name, ads_cost, impression, click
      - name: product
        identifier: raw_gz_product
        description: details about data produts. purchSE _PRICE, products_id 
        tests:
          - not_null:
              column_name: products_id
          - unique:
              column_name: products_id
      - name: sales
        identifier: raw_gz_sales
        description: details about data sales. date_date, orders_id, products_id, revenue, quantity
        tests:
          - not_null:
              column_name: orders_id
          - not_null:
              column_name: products_id
      - name: ship
        identifier: raw_gz_ship
        description: details about data ship. orders_id, shipping_fee, logCost, ship_cost
        tests:
          - not_null:
              column_name: orders_id
          - unique:
              column_name: orders_id

          
